name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
      with:
        rust-version: stable
    - uses: actions/checkout@v3
    - name: Check formatting
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy -- -D warnings -W clippy::pedantic
    - name: markdownlint
      uses: articulate/actions-markdownlint@v1

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - name: Install Redis on Ubuntu
      if: matrix.os == 'ubuntu-latest'
      run: sudo apt-get install -y redis-tools redis-server
    - name: Verify that redis is running
      if: matrix.os == 'ubuntu-latest'
      run: redis-cli ping
    - name: Install Redis on Mac
      if: matrix.os == 'macOS-latest'
      run: brew install redis
    - name: Start Redis on Mac
      if: matrix.os == 'macOS-latest'
      run: brew services start redis
    - name: Install Rust
      uses: hecrj/setup-rust-action@v1
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Stop services if on mac
      if: matrix.os == 'macOS-latest'
      run: brew services stop redis
